#!/usr/bin/env ruby
require 'net/http'

if ARGV.length < 3
    warn "Usage: dummy_image  x_size y_size text"
    exit 0
end
x = ARGV[0]
y = ARGV[1]
name = ARGV[2..-1].join("-")
filename = ARGV[2..-1].join("_") + ".jpg"
url = URI.parse("http://dummyimage.com/#{x}x#{y}/000/fff&text=#{name}")
req = Net::HTTP::Get.new(url.path)
res = Net::HTTP.start(url.host, url.port) do |http|
    http.request(req)
end

File.open(filename, "w+") { |file| file << res.body  }

